/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonDialog: typeof import('./src/components/cus-ui/dialog/CommonDialog.vue')['default']
    CommonModal: typeof import('./src/components/cus-ui/modal/CommonModal.vue')['default']
    CusButton: typeof import('./src/components/cus-ui/button/CusButton.vue')['default']
    CusCard: typeof import('./src/components/cus-ui/card/CusCard.vue')['default']
    CusCircularProgress: typeof import('./src/components/cus-ui/progress/CusCircularProgress.vue')['default']
    CusHr: typeof import('./src/components/cus-ui/hr/CusHr.vue')['default']
    CusInput: typeof import('./src/components/cus-ui/input/CusInput.vue')['default']
    CusLink: typeof import('./src/components/cus-ui/link/CusLink.vue')['default']
    CusPopover: typeof import('./src/components/cus-ui/popover/CusPopover.vue')['default']
    CusSelect: typeof import('./src/components/cus-ui/select/CusSelect.vue')['default']
    CusSidebar: typeof import('./src/components/cus-ui/sidebar/CusSidebar.vue')['default']
    CusSpace: typeof import('./src/components/cus-ui/space/CusSpace.vue')['default']
    CusSpinning: typeof import('./src/components/cus-ui/spinning/CusSpinning.vue')['default']
    CusToast: typeof import('./src/components/cus-ui/toast/CusToast.vue')['default']
    CusToggle: typeof import('./src/components/cus-ui/toggle/CusToggle.vue')['default']
    CusTooltip: typeof import('./src/components/cus-ui/tooltip/CusTooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
