/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {RouteRecordInfo} from 'unplugin-vue-router/types';
  
  /**
	 * Route name map generated by unplugin-vue-router
	 */
	export interface RouteNamedMap {
		'管理 - 仪表盘': RouteRecordInfo<'管理 - 仪表盘', '/admin/home', Record<never, never>, Record<never, never>>,
		'管理后台 - 登录': RouteRecordInfo<'管理后台 - 登录', '/admin/login', Record<never, never>, Record<never, never>>,
		'管理 - 角色管理': RouteRecordInfo<'管理 - 角色管理', '/admin/role', Record<never, never>, Record<never, never>>,
		'观众': RouteRecordInfo<'观众', '/audience', Record<never, never>, Record<never, never>>,
		'直播中': RouteRecordInfo<'直播中', '/broadcast', Record<never, never>, Record<never, never>>,
		'/broadcast/BroadcastEndPage': RouteRecordInfo<'/broadcast/BroadcastEndPage', '/broadcast/BroadcastEndPage', Record<never, never>, Record<never, never>>,
		'/broadcast/BroadcastPreparePage': RouteRecordInfo<'/broadcast/BroadcastPreparePage', '/broadcast/BroadcastPreparePage', Record<never, never>, Record<never, never>>,
		'/test/test': RouteRecordInfo<'/test/test', '/test/test', Record<never, never>, Record<never, never>>,
		'/test/video': RouteRecordInfo<'/test/video', '/test/video', Record<never, never>, Record<never, never>>,
		'用户 - 直播页': RouteRecordInfo<'用户 - 直播页', '/user/home', Record<never, never>, Record<never, never>>,
	}
}
